CREATE TABLE IF NOT EXISTS products (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,                 -- external product id
    external_id   BIGINT UNIQUE,                 -- external product id
    name          VARCHAR(30)     NOT NULL,           -- trimmed product title
    handle        TEXT,
    vendor        TEXT,
    product_type  TEXT,
    tags          TEXT,
    created_at    TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMPTZ
    );

-- VARIANTS
CREATE TABLE IF NOT EXISTS product_variants (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,            -- external variant id
    external_id        BIGINT UNIQUE NOT NULL,
    product_id         BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    title              TEXT   NOT NULL,               -- e.g. "White / XS"
    sku                TEXT,
    available          BOOLEAN        NOT NULL DEFAULT FALSE,
    requires_shipping  BOOLEAN        NOT NULL DEFAULT TRUE,
    taxable            BOOLEAN        NOT NULL DEFAULT TRUE,
    price              NUMERIC(12,2),
    grams              INTEGER,
    position           INTEGER,
    created_at         TIMESTAMPTZ,
    updated_at         TIMESTAMPTZ
    );
